### PR TITLE
Fix

### PR DESCRIPTION
**Pull request by SBoonstraABT**
- Reordered parsing for GEF.
- Replacing NaN values with 0 in correction for inclination.

This way, column voids are handled before the data is used (which is safer). Accordingly, issues that arrise from the NaN values being used can be dealt with. Which is the case for values in the inclination in the function `correct_depth_with_inclination`, which has been dealt with  by temporarily replacing NaN values by zero before they are used.

This fix resolves issue [issue #57 ](https://github.com/ritchie46/pygef/issues/57).

### CODE REVIEW

**Comment by martinapippi** [comment]
Thanks for the contribution! Could you also add a unit test with the example that was not working correctly before this change?

**Comment by SBoonstraABT** [comment]
My pleasure! I have added the unit test with a minimal working example of the CPT from which the problem arose.

**Comment by martinapippi** [comment]
Last request: could you also use `black .`(pip install black) to format the files? Otherwise the build will fail on the master (we should really add this check in the PR).

**Comment by SBoonstraABT** [comment]
No problem, I used black to auto-format the files

**Pull request merged**
